### PR TITLE
Add support for converting from facelet level to cubie level

### PR DESCRIPTION
**Pull request by vmiklos**
The the concepts, see <http://kociemba.org/math/faceletlevel.htm> and <http://kociemba.org/math/cubielevel.htm>, this code implements those ideas.

Also add a testcase that assert that just the conversion itself is correct. A manual integration test is possible, given the documented scramble and expected solution.

Fixes <https://github.com/luckasRanarison/kewb/issues/1>.

### CODE REVIEW

**Comment by vmiklos** [comment]
Oh, a merge conflict. I'll look at resolving that.

**Comment by luckasRanarison** [comment]
The PR looks good, you just have to pull the changes and move the files to ```src/cube/``` instead of ```cube/```. It should resolve the conflicts.

**Comment by vmiklos** [comment]
No worries, will rebase.

**Comment by vmiklos** [comment]
OK, should be rebased now. :-)

**Comment by vmiklos** [comment]
One small thing I forgot is that in case src/lib.rs exports State, then FaceCube should be exported there as well, fixed now.

**Comment by luckasRanarison** [comment]
Thanks again for the PR :), I'm going to publish it in few minutes

**Pull request merged**
