### PR TITLE
cli: add a --facelet flag to the solve command

### PR DESCRIPTION
**Pull request by vmiklos**
Either the existing --scramble or the new --facelet has to be specified.

Fixes <https://github.com/luckasRanarison/kewb/issues/5>.

### CODE REVIEW

**Comment by luckasRanarison** [comment]
Thanks again for the PR :)! I'm not on my computer, right now but I'll publish it tomorro.

**Comment by vmiklos** [comment]
Do it as you like, I personally build the binary crate from git, so no hurry. :)

Some other random thoughts:

- I built a simple "expose this as json webservice" thing on top of this library + a web-based UI for it, perhaps it's interesting: https://share.vmiklos.hu/pages/rubik/
- It may make sense to enable github discussions for this repo? It would allow discussing things like error handling, which is not an issue per se, but maybe it could be improved (Result<_, String> and then all this unwrap()).

**Comment by luckasRanarison** [comment]
Your project is really cool! (I noticed a small bug: there seems to be an offset with the click if you scroll the page). I've also wanted to create a web UI, I hope I'll do it one day...
This is my second Rust project, and I'm still not entirely familiar with best practices, so feedback is definitely welcome! I've enabled the discussion as you suggested :)

**Comment by vmiklos** [comment]
> (I noticed a small bug: there seems to be an offset with the click if you scroll the page

Good catch, [fixed](https://github.com/vmiklos/vmexam/commit/98b50890a35deaaf7d839d38ce7eb265a7cb12b5), hopefully.

> I've enabled the discussion as you suggested :)

Thanks, will open a thread there instead of misusing this PR.

**Pull request merged**
